### ISSUE TITLE
apple music未対応ですか？

### ISSUE THREAD

**Issue by kuraim22** [tumugin/NowPlayingV2#1]
なうぷれTunesV2リリースありがとうございます。
使いやすくてデザインも最高です。

アプリについて１つ質問があります。
自分のローカルの音楽やapple musicからダウンロードしたファイルは再生中に反映されますが、
apple musicの未ダウンロードストリーミング再生中の曲は再生中に反映されないようです。

apple musicヘビーユーザーなのでストリーミング再生にも対応していただければありがたいです。
よろしくお願いします！

**Comment by tumugin** [comment]
バグ報告ありがとうございます。
手元の環境でバグが再現できましたので、次回リリース時に修正させていただきます。

**Comment by tumugin** [comment]
fixed bcd72b9.

**Comment by kuraim22** [comment]
ありがとうございます (^^♪
