### ISSUE TITLE
曲から取得できる情報項目の追加

### ISSUE THREAD

**Issue by proghani** [tumugin/NowPlayingV2#2]
V2リリースありがとうございます。大変気に入っております。
バグ報告などでなく機能のリクエストとなってしまい恐縮ですが、曲のプロパティから「グループ」の項目内容を取得するようにしていただくことは可能でしょうか。「$Group」などのタグで。

個人的にはアーティストの出身国をここに入力してソートしていたので、それがあると大変うれしいです。また旧なうぷれでは対応していました。

ご検討よろしくお願いいたします。

**Comment by tumugin** [comment]
機能追加のご要望ありがとうございます。
コードの方には既に反映したので、次回リリース時に使用できるようになります。
