### ISSUE TITLE
アートワークのサイズが大きい場合の動作

### ISSUE THREAD

**Issue by kawasemi6** [tumugin/NowPlayingV2#3]
V2リリースありがとうございました。
Windows10 + iTunes環境で動作させていて気がついた点を1点報告させてもらいます。
楽曲に設定しているアートワークのサイズが大きすぎる場合に曲の情報が全く取得できないようです。
(具体的なサイズは確認できてないです)
一度アートワークのサイズが大きい曲を再生するとそれ以降の別の曲の情報も取れていないようです。
可能ならばアートワーク以外の情報は最低限毎回取れるような形になったりしないでしょうか？

**Comment by tumugin** [comment]
@kawasemi6 さん
Issue報告ありがとうございます。
MusicBeeでも似たような現象が以前あったので(今は既に解決済み)、もしかしたらプロセス間通信周りの問題かもしれないです。
今週末に基本情報技術者試験を控えてるので終わり次第検証してみます。

**Comment by tumugin** [comment]
MEMO: Might be related to commit 24486c1.

**Comment by tumugin** [comment]
修正完了しました。
