### ISSUE TITLE
iTunes12.7.4.80での動作

### ISSUE THREAD

**Issue by warioji** [tumugin/NowPlayingV2#4]
iTunes12.7.4.80でなうぷれTunesが動作しなくなってしまっているようです。
もしよろしければ対応の方お願い致します。

**Comment by tumugin** [comment]
@warioji さん
Issue報告ありがとうございます。
iTunes12.7.4.80をクリーンインストールした環境で検証してみましたが、正常に動作しているようです。
一度iTunesの入れ直しを試して頂けないでしょうか? また、OSや使用しているウイルス対策ソフト等使用環境について詳しく教えて頂けないでしょうか？
よろしくお願いいたします。

**Comment by warioji** [comment]
@tumugin 様
なんてこった。iTunes12.7.4.80の再インストール、及びセキュリティソフト(AVG)の停止を試しましたが、状況は変わりませんでした。
他に何か原因と考えるものはありますでしょうか。iTunesNPPlugin.exeが起動しているのはタスクマネージャで確認できました。

**Comment by warioji** [comment]
書き忘れていました。OSはWindows10のFCUです。

**Comment by tumugin** [comment]
お手数ですが、一度なうぷれTunesからiTunesNPPlugin.exeの起動を無効化した上で、なうぷれTunes本体のみを立ち上げて、以下のデバッグ用のiTunesNPPluginを試して頂けないでしょうか？
[iTunesNPPlugin_Debug.zip](https://github.com/tumugin/NowPlayingV2/files/1951215/iTunesNPPlugin_Debug.zip)
正常に動作している環境でiTunesから曲を再生すると、この様なデバッグ用メッセージが表示されますが、この画面のスクリーンショットを送って頂けないでしょうか？(終了時は普通に×ボタンで終了で構いません)
![snapcrab_cuserskazukidocumentssourcecodenowplayingv2nowplayingv2bindebugitunesnppluginexe_2018-4-26_21-53-27_no-00](https://user-images.githubusercontent.com/1785179/39307116-f3e8ebb2-499c-11e8-859d-ec84f572c3f3.png)

**Comment by tumugin** [comment]
考えられる原因としては、(予想ですが)iTunesとの接続が何らかの原因で上手く行っていないか、プロセス間通信が何らかの理由で阻害されている、の2つです。
前者の場合、大抵はiTunesのCOMコンポーネントが正しくシステムに登録されていなかったりで、iTunesの再インストールで直る事が多いのですが...

**Comment by warioji** [comment]
どうやらiTunesNPPlugin.exeが原因なんですかね…？
頂いたexeを使用すると何も問題なく曲情報取得が出来ているようです。
元に戻すとやはり何も再生されていない旨が表示されてしまいます。
![2018-04-26 22 30 59](https://user-images.githubusercontent.com/2115770/39308914-aca837a8-49a1-11e8-96bb-db00a7d12310.png)

**Comment by tumugin** [comment]
@warioji さん
ご報告ありがとうございます。
何度もいろいろ試して頂き申し訳ないのですが、一度なうぷれTunesが入っているフォルダから`Interop.iTunesAdminLib.dll`と`Interop.iTunesLib.dll`を削除してみてから、元の状態で起動するとどうなりますでしょうか？

**Comment by warioji** [comment]
両ファイルともフォルダ内に見当たりませんでした。念の為NowPlayingV2_1200.zipをDLし直したのですが、その中にも無いようです。他のファイルということでしょうか？

**Comment by warioji** [comment]
大変申し訳無いです。iTunes再インストールしたあと、再起動をサボっていることを忘れており、再起動したら通常のiTunesNPPlugin.exeで動作しました。
お騒がせして大変申し訳ありませんでした、ありがとうございました！

**Comment by tumugin** [comment]
いえいえ～ 直ってよかったです。
