### ISSUE TITLE
今すぐツイートした際にNullになる件

### ISSUE THREAD

**Issue by kawasemi6** [tumugin/NowPlayingV2#6]
先日はアルバムアートの件に対応していただきありがとうございました。
連続になって申し訳ないのですが、また1点要望があります。
設定で「ツイートにアルバムアートを添付する」の設定が有効の場合に、アルバムアートが設定されていない曲を「今すぐツイートする」から投稿しようとすると「値をNullにすることはできません」とエラーになってしまいます。
曲にアルバムアートがない場合は自動で無しで投稿できるようにはできないものでしょうか？
![image](https://user-images.githubusercontent.com/36789161/41812081-17f77860-7757-11e8-8359-014be1a46765.png)

**Comment by tumugin** [comment]
issueのご報告ありがとうございます。
バグですので次回リリースの際に修正させて頂きます。

**Comment by tumugin** [comment]
バグの修正の方は終わりましたので、次回リリースのものにFixを反映させていただきます。
