### ISSUE TITLE
自動ツイート機能について

### ISSUE THREAD

**Issue by Miutaku** [tumugin/NowPlayingV2#7]
「前回のツイートから一定時間経過していない場合はツイートしない」の設定において、分単位になっていますがこれを秒単位にしていただくことはできませんか。よろしくおねがいします。

**Comment by tumugin** [comment]
ご要望ありがとうございます。
現在Mac版の開発に伴い、自動ツイートなどのコア機能の共通ソース化を進めているので、それに合わせて実装したいと考えております。

**Comment by tumugin** [comment]
実装しました。
